"""update quota metrics

Revision ID: dae71faa437f
Revises: 0c6718bf1564
Create Date: 2026-02-20 13:44:46.681696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae71faa437f'
down_revision: Union[str, Sequence[str], None] = '0c6718bf1564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotas', sa.Column('file_processing', sa.Integer(), server_default=sa.text('10'), nullable=False))
    op.drop_index(op.f('ix_quotas_user_id'), table_name='quotas')
    op.create_index('ix_quotas_user_id', 'quotas', ['user_id'], unique=False)
    op.drop_column('quotas', 'embedding_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotas', sa.Column('embedding_tokens', sa.INTEGER(), server_default=sa.text('50000'), autoincrement=False, nullable=False))
    op.drop_index('ix_quotas_user_id', table_name='quotas')
    op.create_index(op.f('ix_quotas_user_id'), 'quotas', ['user_id'], unique=True)
    op.drop_column('quotas', 'file_processing')
    # ### end Alembic commands ###
