"""remove runtime context from conversation model

Revision ID: e54376c58563
Revises: 9aef779df382
Create Date: 2026-02-22 14:29:15.922780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e54376c58563'
down_revision: Union[str, Sequence[str], None] = '9aef779df382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'runtime_context')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('runtime_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
