"""update quota limits: add  web scraping limits

Revision ID: 4a3ae2fe6c68
Revises: e54376c58563
Create Date: 2026-02-23 18:29:29.940432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3ae2fe6c68'
down_revision: Union[str, Sequence[str], None] = 'e54376c58563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotas', sa.Column('web_scraping', sa.Integer(), server_default=sa.text('10'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotas', 'web_scraping')
    # ### end Alembic commands ###
