"""add quota model

Revision ID: 1814ba4c3eb3
Revises: 71d736d805c6
Create Date: 2026-02-18 23:55:40.762605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1814ba4c3eb3'
down_revision: Union[str, Sequence[str], None] = '71d736d805c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotas',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('files', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('storage_bytes', sa.Integer(), server_default=sa.text('104857600'), nullable=False),
    sa.Column('conversations', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('web_searches', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('image_generations', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('video_generations', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('llm_tokens', sa.Integer(), server_default=sa.text('50000'), nullable=False),
    sa.Column('embedding_tokens', sa.Integer(), server_default=sa.text('50000'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotas_user_id', 'quotas', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotas_user_id', table_name='quotas')
    op.drop_table('quotas')
    # ### end Alembic commands ###
